platform :ios, '8.0'

target 'CCLocalLibrary-Swift' do
  use_frameworks!

  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Alamofire', '~> 4.5.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2.0'
  pod 'Kingfisher', '~> 3.10.2'

end
